[project]
name = "k8-expert"
version = "0.1.0"
dependencies = [
    "python-dotenv", 
    "pydantic-ai",
    "chainlit",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
